name: AdvancedHelp
main: me.codedred.advancedhelp.AdvancedHelp
 # keeping author as 'Cmaaxx' for Metrics purposes.
author: Cmaaxx
authors: [CodedRed, Fjc]
version: 1.12.7
api-version: 1.21
softdepend: [PlaceholdersAPI, HeadDatabase, PlaceholderAPI]
loadbefore: [Essentials, CMI, EssentialsX]

commands:
  help:
    description: Use /help to see the help section.
    usage: /<command>
    permission: help.use
    aliases: ehelp
  ahelp:
    description: Admin help for AdvancedHelp.
    usage: /<command>
    permission: help.reload
    aliases: advancedhelp
